name: mafaulda_gpu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-learn
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch
